{
  "backend": {
    "name": "test-repo",
    "branch": master,
  },
  "media_folder": "static/assets",
  "public_folder": "assets",
  "collections": [
    {
      "name": "blog-en",
      "label": "Blog (EN)",
      "folder": "src/pages/blog/",
      "create": true,
      "extension": "en.md",
      "format": "frontmatter",
      "fields": [
        {
          "label": "Template Key",
          "name": "templateKey",
          "widget": "hidden",
          "default": "blog-post"
        },
        {
          "label": "Title",
          "name": "title",
          "widget": "string"
        },
        {
          "label": "Publish Date",
          "name": "date",
          "widget": "datetime"
        },
        {
          "label": "Description",
          "name": "description",
          "widget": "text"
        },
        {
          "label": "Body",
          "name": "body",
          "widget": "markdown"
        },
        {
          "label": "Tags",
          "name": "tags",
          "widget": "list"
        }
      ]
    },
    {
      "name": "blog-de",
      "label": "Blog (DE)",
      "folder": "src/pages/blog/",
      "create": true,
      "extension": "de.md",
      "format": "frontmatter",
      "fields": [
        {
          "label": "Template Key",
          "name": "templateKey",
          "widget": "hidden",
          "default": "blog-post"
        },
        {
          "label": "Title",
          "name": "title",
          "widget": "string"
        },
        {
          "label": "Publish Date",
          "name": "date",
          "widget": "datetime"
        },
        {
          "label": "Description",
          "name": "description",
          "widget": "text"
        },
        {
          "label": "Body",
          "name": "body",
          "widget": "markdown"
        },
        {
          "label": "Tags",
          "name": "tags",
          "widget": "list"
        }
      ]
    },
    {
      "name": "pages",
      "label": "Pages",
      "files": [
        {
          "file": "src/pages/index.en.md",
          "label": "Home Page (EN)",
          "name": "index-en",
          "fields": [
            {
              "label": "Metadata",
              "name": "metadata",
              "widget": "object",
              "fields": [
                {
                  "label": "Meta Title",
                  "name": "metaTitle",
                  "widget": "string"
                },
                {
                  "label": "Meta Description",
                  "name": "metaDescription",
                  "widget": "string"
                }
              ]
            },
            {
              "label": "Heading",
              "name": "heading",
              "widget": "string"
            },
            {
              "label": "Redirect Button Text",
              "name": "redirectButtonText",
              "widget": "string"
            }
          ]
        },
        {
          "file": "src/pages/index.de.md",
          "label": "Home Page (DE)",
          "name": "index-de",
          "fields": [
            {
              "label": "Metadata",
              "name": "metadata",
              "widget": "object",
              "fields": [
                {
                  "label": "Meta Title",
                  "name": "metaTitle",
                  "widget": "string"
                },
                {
                  "label": "Meta Description",
                  "name": "metaDescription",
                  "widget": "string"
                }
              ]
            },
            {
              "label": "Heading",
              "name": "heading",
              "widget": "string"
            },
            {
              "label": "Redirect Button Text",
              "name": "redirectButtonText",
              "widget": "string"
            }
          ]
        },
        {
          "file": "src/pages/about/index.en.md",
          "label": "About Page (EN)",
          "name": "about-en",
          "fields": [
            {
              "label": "Metadata",
              "name": "metadata",
              "widget": "object",
              "fields": [
                {
                  "label": "Meta Title",
                  "name": "metaTitle",
                  "widget": "string"
                },
                {
                  "label": "Meta Description",
                  "name": "metaDescription",
                  "widget": "string"
                }
              ]
            },
            {
              "label": "Redirect Button Text",
              "name": "redirectButtonText",
              "widget": "string"
            }
          ]
        },
        {
          "file": "src/pages/about/index.de.md",
          "label": "About Page (DE)",
          "name": "about-de",
          "fields": [
            {
              "label": "Metadata",
              "name": "metadata",
              "widget": "object",
              "fields": [
                {
                  "label": "Meta Title",
                  "name": "metaTitle",
                  "widget": "string"
                },
                {
                  "label": "Meta Description",
                  "name": "metaDescription",
                  "widget": "string"
                }
              ]
            },
            {
              "label": "Redirect Button Text",
              "name": "redirectButtonText",
              "widget": "string"
            }
          ]
        }
      ]
    }
  ]
}